export const store = [
  {
    id: 1,
    name: '숭실 김밥천국',
    lat: 37.496204,
    lng: 126.957355,
    storeType: 'Korean',
    storeLink: 'https://example.com/kimchunguk',
    isStoreRegistered: true,
    image: 'https://example.com/images/store1.jpg',
    university: '숭실대학교',
    menu: [
      {
        id: 0,
        image: 'https://example.com/images/gimbap.jpg',
        name: '김밥',
        price: 3500,
        discountPrice: null,
        isDiscounted: false,
      },
    ],
  },
  {
    id: 2,
    name: '숭실 불고기집',
    lat: 37.495842,
    lng: 126.956728,
    storeType: 'Korean',
    storeLink: 'https://example.com/bulgogi',
    isStoreRegistered: true,
    image: 'https://example.com/images/store2.jpg',
    university: '숭실대학교',
    menu: [
      {
        id: 0,
        image: 'https://example.com/images/bulgogi.jpg',
        name: '불고기',
        price: 12000,
        discountPrice: 11000,
        isDiscounted: true,
      },
    ],
  },
  {
    id: 3,
    name: '숭실 중화반점',
    lat: 37.496783,
    lng: 126.956431,
    storeType: 'Chinese',
    storeLink: 'https://example.com/junghwa',
    isStoreRegistered: true,
    image: 'https://example.com/images/store3.jpg',
    university: '숭실대학교',
    menu: [
      {
        id: 0,
        image: 'https://example.com/images/jajangmyeon.jpg',
        name: '짜장면',
        price: 6000,
        discountPrice: null,
        isDiscounted: false,
      },
    ],
  },
  {
    id: 4,
    name: '숭실 버거킹',
    lat: 37.496204,
    lng: 126.957112,
    storeType: 'Fast Food',
    storeLink: 'https://example.com/burgerking',
    isStoreRegistered: true,
    image: 'https://example.com/images/store4.jpg',
    university: '숭실대학교',
    menu: [
      {
        id: 0,
        image: 'https://example.com/images/whopper.jpg',
        name: '와퍼',
        price: 8500,
        discountPrice: 8000,
        isDiscounted: true,
      },
    ],
  },
  {
    id: 5,
    name: '숭실 파스타집',
    lat: 37.495324,
    lng: 126.955875,
    storeType: 'Italian',
    storeLink: 'https://example.com/pastahouse',
    isStoreRegistered: true,
    image: 'https://example.com/images/store5.jpg',
    university: '숭실대학교',
    menu: [
      {
        id: 0,
        image: 'https://example.com/images/carbonara.jpg',
        name: '까르보나라',
        price: 12000,
        discountPrice: null,
        isDiscounted: false,
      },
    ],
  },
  {
    id: 6,
    name: '숭실 카페',
    lat: 37.495414,
    lng: 126.956195,
    storeType: 'Cafe',
    storeLink: 'https://example.com/cafe',
    isStoreRegistered: true,
    image: 'https://example.com/images/store6.jpg',
    university: '숭실대학교',
    menu: [
      {
        id: 0,
        image: 'https://example.com/images/americano.jpg',
        name: '아메리카노',
        price: 4000,
        discountPrice: null,
        isDiscounted: false,
      },
    ],
  },
  {
    id: 7,
    name: '숭실 고기집',
    lat: 37.495954,
    lng: 126.955685,
    storeType: 'Korean',
    storeLink: 'https://example.com/gogijip',
    isStoreRegistered: true,
    image: 'https://example.com/images/store7.jpg',
    university: '숭실대학교',
    menu: [
      {
        id: 0,
        image: 'https://example.com/images/samgyeopsal.jpg',
        name: '삼겹살',
        price: 15000,
        discountPrice: null,
        isDiscounted: false,
      },
    ],
  },
  {
    id: 8,
    name: '숭실 돈까스',
    lat: 37.495774,
    lng: 126.955845,
    storeType: 'Japanese',
    storeLink: 'https://example.com/donkatsu',
    isStoreRegistered: true,
    image: 'https://example.com/images/store8.jpg',
    university: '숭실대학교',
    menu: [
      {
        id: 0,
        image: 'https://example.com/images/donkatsu.jpg',
        name: '왕돈까스',
        price: 10000,
        discountPrice: null,
        isDiscounted: false,
      },
    ],
  },
  {
    id: 9,
    name: '숭실 도시락',
    lat: 37.495314,
    lng: 126.955445,
    storeType: 'Korean',
    storeLink: 'https://example.com/dosirak',
    isStoreRegistered: true,
    image: 'https://example.com/images/store9.jpg',
    university: '숭실대학교',
    menu: [
      {
        id: 0,
        image: 'https://example.com/images/dosirak.jpg',
        name: '제육볶음 도시락',
        price: 7000,
        discountPrice: null,
        isDiscounted: false,
      },
    ],
  },
  {
    id: 10,
    name: '숭실 피자헛',
    lat: 37.496213,
    lng: 126.957456,
    storeType: 'Pizza',
    storeLink: 'https://example.com/pizzahut',
    isStoreRegistered: true,
    image: 'https://example.com/images/store10.jpg',
    university: '숭실대학교',
    menu: [
      {
        id: 0,
        image: 'https://example.com/images/pepperonipizza.jpg',
        name: '페퍼로니 피자',
        price: 15000,
        discountPrice: 14000,
        isDiscounted: true,
      },
    ],
  },
  {
    id: 11,
    name: '숭실 삼계탕',
    lat: 37.495934,
    lng: 126.956785,
    storeType: 'Korean',
    storeLink: 'https://example.com/samgyetang',
    isStoreRegistered: true,
    image: 'https://example.com/images/store11.jpg',
    university: '숭실대학교',
    menu: [
      {
        id: 0,
        image: 'https://example.com/images/samgyetang.jpg',
        name: '삼계탕',
        price: 13000,
        discountPrice: null,
        isDiscounted: false,
      },
    ],
  },
  {
    id: 12,
    name: '숭실 덮밥',
    lat: 37.496034,
    lng: 126.956545,
    storeType: 'Korean',
    storeLink: 'https://example.com/deopbap',
    isStoreRegistered: true,
    image: 'https://example.com/images/store12.jpg',
    university: '숭실대학교',
    menu: [
      {
        id: 0,
        image: 'https://example.com/images/deopbap.jpg',
        name: '제육덮밥',
        price: 7500,
        discountPrice: null,
        isDiscounted: false,
      },
    ],
  },
  {
    id: 13,
    name: '숭실 초밥',
    lat: 37.496154,
    lng: 126.956345,
    storeType: 'Japanese',
    storeLink: 'https://example.com/sushi',
    isStoreRegistered: true,
    image: 'https://example.com/images/store13.jpg',
    university: '숭실대학교',
    menu: [
      {
        id: 0,
        image: 'https://example.com/images/sushi.jpg',
        name: '모둠 초밥',
        price: 18000,
        discountPrice: null,
        isDiscounted: false,
      },
    ],
  },
  {
    id: 14,
    name: '숭실 파스타집',
    lat: 37.495834,
    lng: 126.955865,
    storeType: 'Italian',
    storeLink: 'https://example.com/pasta',
    isStoreRegistered: true,
    image: 'https://example.com/images/store14.jpg',
    university: '숭실대학교',
    menu: [
      {
        id: 0,
        image: 'https://example.com/images/pasta.jpg',
        name: '볼로네제 파스타',
        price: 13000,
        discountPrice: null,
        isDiscounted: false,
      },
    ],
  },
  {
    id: 15,
    name: '숭실 국밥집',
    lat: 37.495724,
    lng: 126.955755,
    storeType: 'Korean',
    storeLink: 'https://example.com/gukbap',
    isStoreRegistered: true,
    image: 'https://example.com/images/store15.jpg',
    university: '숭실대학교',
    menu: [
      {
        id: 0,
        image: 'https://example.com/images/gukbap.jpg',
        name: '돼지국밥',
        price: 8000,
        discountPrice: 7500,
        isDiscounted: true,
      },
    ],
  },
]
